import { Finding } from '../types';

export interface RemediationBundle {
  patchContent: string;
  remediatedCodeContent: string;
  totalFixesCount: number;
}

/**
 * Generates a unified Git patch (.patch) and consolidated remediation HCL file
 * from findings that contain fix snippets.
 */
export const generateRemediationBundle = (
  findings: Finding[],
  originalCode?: string
): RemediationBundle => {
  const fixableFindings = findings.filter(f => f.fix && f.fix.trim().length > 0);

  if (fixableFindings.length === 0) {
    return {
      patchContent: '# No automated fixes available for current findings.',
      remediatedCodeContent: originalCode || '# No code fixes available.',
      totalFixesCount: 0
    };
  }

  // 1. Build Unified Git Patch
  const timestamp = new Date().toISOString();
  let patch = `# ========================================================\n`;
  patch += `# DRA Automated Remediation Patch\n`;
  patch += `# Generated: ${timestamp}\n`;
  patch += `# Total Remediations: ${fixableFindings.length}\n`;
  patch += `# To apply: git apply dra-remediation.patch\n`;
  patch += `# ========================================================\n\n`;

  // Group fixes by fileName
  const byFile: Record<string, Finding[]> = {};
  fixableFindings.forEach(f => {
    const fn = f.fileName || 'main.tf';
    if (!byFile[fn]) byFile[fn] = [];
    byFile[fn].push(f);
  });

  Object.entries(byFile).forEach(([fileName, fileFindings]) => {
    patch += `diff --git a/${fileName} b/${fileName}\n`;
    patch += `--- a/${fileName}\n`;
    patch += `+++ b/${fileName}\n`;

    fileFindings.forEach((f, idx) => {
      const line = f.lineNumber && f.lineNumber > 0 ? f.lineNumber : 1;
      patch += `@@ -${line},1 +${line},${(f.fix?.split('\n').length || 1) + 2} @@ [DRA Finding ${idx + 1}: ${f.title}]\n`;
      patch += `+ # DRA-FIX [${f.severity.toUpperCase()}]: ${f.title}\n`;
      if (f.compliance && f.compliance.length > 0) {
        patch += `+ # Compliance: ${f.compliance.map(c => `${c.standard} (${c.controlId})`).join(', ')}\n`;
      }
      const fixLines = (f.fix || '').trim().split('\n');
      fixLines.forEach(l => {
        patch += `+ ${l}\n`;
      });
      patch += `\n`;
    });
  });

  // 2. Build Consolidated Remediation File
  let remediatedFile = `# ========================================================\n`;
  remediatedFile += `# DRA RECOMMENDED REMEDIATION FILE\n`;
  remediatedFile += `# Automatically generated by Deployment Readiness Auditor\n`;
  remediatedFile += `# Date: ${timestamp}\n`;
  remediatedFile += `# ========================================================\n\n`;

  fixableFindings.forEach((f, idx) => {
    remediatedFile += `# --------------------------------------------------------\n`;
    remediatedFile += `# Finding ${idx + 1} [${f.severity.toUpperCase()}]: ${f.title}\n`;
    remediatedFile += `# Location: ${f.fileName || 'main.tf'}:${f.lineNumber || 1}\n`;
    if (f.compliance && f.compliance.length > 0) {
      remediatedFile += `# Standards: ${f.compliance.map(c => `${c.standard} ${c.controlId}`).join(' | ')}\n`;
    }
    remediatedFile += `# Explanation: ${f.remediation}\n`;
    remediatedFile += `# --------------------------------------------------------\n`;
    remediatedFile += `${f.fix?.trim()}\n\n`;
  });

  return {
    patchContent: patch,
    remediatedCodeContent: remediatedFile,
    totalFixesCount: fixableFindings.length
  };
};

/**
 * Triggers a browser file download for text content.
 */
export const downloadTextFile = (filename: string, content: string) => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
